import Home from './HomePage'
import About from './AboutPage'
import Checkout from './CheckoutPage'
import Cart from './CartPage'
import Products from './ProductsPage'
import SingleProduct from './SingleProductPage'
import Error from './ErrorPage'
import Private from './PrivateRoute'
import AuthWrapper from './AuthWrapper'
export {Home,About,Products,SingleProduct,Cart,Checkout,Error,Private,AuthWrapper}